title: Test site
author: Dastan Pratov
email: somemail@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My site is the best ever.

# social links
twitter_username: DastanPratov
github_username:  DastanPratov

show_excerpts: i am tired to pass this course
theme: minima
